{% set version = "4.0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-preseqr
  version: {{ version|replace("-", "_") }}

source:
  fn: preseqR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/preseqR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/preseqR/preseqR_{{ version }}.tar.gz
  sha256: 0143db473fb9a811f9cf582a348226a5763e62d9857ce3ef4ec41412abb559bc

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-polynom

  run:
    - r-base
    - r-polynom

test:
  commands:
    - $R -e "library('preseqR')"  # [not win]
    - "\"%R%\" -e \"library('preseqR')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=preseqR
  license: GPL-3
  summary: The relation between the number of species and the number of individuals in a random
    sample is a classic problem back to Fisher (1943) <doi:10.2307/1411>. We generalize
    this problem to estimate the number of species represented at least r times in a
    random sample. In particular when r=1, it becomes the classic problem. We use a
    mixture of Poisson processes to model sampling procedures and apply a nonparametric
    empirical Bayes approach to obtain an estimator. For more information on 'preseqR',
    see Deng C, Daley T and Smith AD (2015) <doi:10.1007/s40484-015-0049-7> and Deng
    C and Smith AD (2016) <arXiv:1607.02804v2>.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
