travis:
  secure:
    BINSTAR_TOKEN: kVW1kSCtOAGZs1ra4l33Xe4GC+zDpnBbqTr0r4Eh1DTEDL5J1KBVdLzAh4qOAGGKEG+rOERuxg10xuo6ZHA3+3/9goEIrJYgT0JCQltCmr7Q6TjsF6Ta2SJZpxBuHxgmLYZ2+FlOWlrtCTKdPBkt4Oi9519mPkYL7QVEilQ/6cxAh4ANc9Vrxwqb9YE6LXi0uvuTFB0y0GVaKz9Cm14GKfDOJjl+iTfshAA5GfnvGH0w/BRco0yBw3M1O4dOQkYHoFgzAhtquaHfwcrI6MY0wi1iE1Xenwnhy43m8svwxPC7btNvDmnWjy9Vvb1x85GnES4j1uv/i3zfPmCHQ6o2AEEA3HI9vlI6SpDOkeJkoxsB/kTuGYFJXPcseKTeZbNDMYLFtzNWE4lxxwMH4kbzQf0IMYEPxHEThI408WDeVD+hLEARwuIwMChwTiIPcxLJXCJCR58IOjxEvTHx8XXzgDcyL6F/O3nuEJ/e3knqfWW2ra6jO3sxpeoRbe/KPq+nAFGG6YEH5bfMvi3t54B+RbpfsCYeZkM/oQG848U2WS2vULe67UlldY+2RZixdna13MvVOTi/zMoVWmQPWoe31PAs0HvsxlnNDqjEYEY0GsnlrxFF6LdQCnpmDIAooenK8Uam7x5/26QQ1kODsfpjOM4grn4aP8rfTD1fXM4yhyE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
