travis:
  secure:
    BINSTAR_TOKEN: ZZzoy1q5pYok9jFKCci6fS90LxaACaWO3/cJK0vUQVwpfjMoumIszKot7PappLFOUuzBUJ8aUb512F3rW5+DXciBJJVTR9wuKIKkXfsbi8VQciK8k63cEwnMDUzJVGNQ+fD63Y/B6Aoa6rMtdjDkQi5vz9NWFGxFaEVk7IaO0aMc/BrzxSOWP/BpQdfeWCk6HJVlqKId0FPfxFg6c1i2I1XCwv1CRBxgdEQIAMja2a3TuOB+zfA3fdtdke5zU34Z7gdAkDrKD6Qo/xTGOdGD2tBDB3Lf2qE+xaWvxCejFMAxvtG8GU9lpagTUvlc1Y00qZSKIhzHBSRGfYYayM9JzKUIhENfgz3SdXyESH+GvtulYgZ9Y3qTa1zPodfwbTYPqgcKu6oVT67cumGbsdb3wQfbr3iTbikCs1WbmlGlJXqy2y6Xn3PmZ7irPPgkqaJQe12HyTSCjZ+iTlafDqzm/yXU6HtcCwr7PdLg+AO1iS/EaPPTdhnHJLJ4na8l9db+4LtDKZmbchOPE8XkZLXLdAnxZYOPXcXLA04pQ/K9tnJjt2Uw8OXqo8GotwtmvXM4cIg8NY8ogr5hfpF4XTx+mXfa+JD8CBdeVXAG8GGEQ69LeRdrJsg+hC1ke3XKDp61WMoWB25dfsmXJML79MQ8TT0QymDHNRFR9v5Io2HCYJI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
