travis:
  secure:
    BINSTAR_TOKEN: 4QiHe6aZ2+If6a5QrJMCyw2oXn5zd/6o+0zq3KoG0BOuYbGe5xKyzFayOqDvOgeqZNBJr/QfcUtn8aJicvL9R/ekt59iPOmrwJklarjbsZT0a6xOqGuSyP9iBnZqCqrCpDEeCwvVVbKAV9fDhH1l/1/Sw5j8roRP4xk3SGQUj14eQLd1jLz44eP9hexKR2fePGPnFki5dBhMW5KDqA8qXL9XoGx5OcrB26lZela3soP763M0QYxn7tp+t93i2RnBAWKb2QXiKEt05Agg2TY0ki2uyNhtZcSY9NGSiMNC8O7y64xMKyyF9gbYdQ9P3tQjRiq1wvtr/5Y8cgr1APssfJ96+Ai7iK2U5hbCYHLBb3eQ+WRYGZNPfQf7xil0yBDHxOOxGqNAVar0ef8e3HQaNsEcRA6YPB4pPfJbkA4pnvM62hGopHzveQjexf8JxNidXM0wYnU15jFlPH93YdMrKBZPv/4BCEPWhEcvOwNLqp0NeABa2r9QF+Jc5ahvf45I1CLG9EEcRWrS5Fdj+iOjxbgd8dRhOXqUY3E+K/QY7sYd9/pJOImVmnaU7izQVMPyxWpgvfncgWwROtMMBf2YbFYEhbZtL9O70roE8flRT423Y5bKZb9T+7D2bOaawSoRP8lDiePNrz5ntmf/2QfGDkfuhrsC/V/6RXjLa/yNkYM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
